const lessonTitle = "最好的圣诞礼物";

const lessonData = [
    // 正文第 1 段
    ["我们", "wǒ men", "we", "kami / kita"],
    ["是", "shì", "were", "adalah"],
    ["餐厅里", "cān tīng lǐ", "in the restaurant", "dalam restoran"],
    ["唯一", "wéi yī", "the only", "satu-satunya"],
    ["带着", "dài zhe", "bringing / with", "membawa"],
    ["小孩", "xiǎo hái", "child", "anak kecil"],
    ["吃饭的", "chī fàn de", "eating meal's", "makan nasi punya"],
    ["家庭", "jiā tíng", "family", "keluarga"],
    ["。", "", "", ""],
    ["我让", "wǒ ràng", "I let", "Saya membiarkan"],
    ["埃里克", "āi lǐ kè", "Eric (Name)", "Eric"],
    ["坐", "zuò", "sit", "duduk"],
    ["在", "zài", "on", "di / atas"],
    ["一张", "yì zhāng", "a (measure word for chair)", "sebuah"],
    ["高椅", "gāo yǐ", "high chair", "kerusi tinggi"],
    ["上", "shàng", "on", "atas"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["注意到", "zhù yì dào", "noticed", "memperhatikan / sedar"],
    ["餐厅里的", "cān tīng lǐ de", "in the restaurant's", "dalam restoran punya"],
    ["每一个人", "měi yí gè rén", "everyone", "setiap orang"],
    ["都", "dōu", "all", "pun"],
    ["安静地", "ān jing de", "quietly", "dengan senyap / bertenang"],
    ["吃着", "chī zhe", "eating", "sedang makan"],
    ["，", "", "", ""],
    ["偶尔", "ǒu ěr", "occasionally / once in a while", "kadang-kala"],
    ["交谈", "jiāo tán", "converse / chat", "berbual / bercakap"],
    ["，", "", "", ""],
    ["也是", "yě shì", "also was", "juga adalah"],
    ["发出", "fā chū", "emitting / making", "mengeluarkan"],
    ["慢轻的", "hěn qīng de", "very soft / low", "yang sangat perlahan"],
    ["声音", "shēng yīn", "sound / voice", "bunyi / suara"],
    ["。", "", "", ""],
    ["突然", "tū rán", "suddenly", "Tiba-tiba"],
    ["，", "", "", ""],
    ["埃里克", "āi lǐ kè", "Eric", "Eric"],
    ["大声地", "dà shēng de", "loudly", "dengan kuat / lantang"],
    ["尖叫", "jiān jiào", "screamed / yelled", "menjerit / melaung"],
    ["起来", "qǐ lái", "up", "mula"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["看", "kàn", "Look", "Tengok"],
    ["，", "", "", ""],
    ["那边", "nà biān", "over there", "sana / di sebelah sana"],
    ["！", "", "", ""],
    ["”", "", "", ""],
    ["他那", "tā nà", "his that", "Dia punya yang"],
    ["胖乎乎的", "pàng hū hū de", "chubby", "chubby / gemuk-gemuk comel"],
    ["小手", "xiǎo shǒu", "small hands", "tangan kecil"],
    ["激动地", "jī dòng de", "excitedly", "dengan teruja / emosi"],
    ["拍打着", "pāi dǎ zhe", "patting / slapping", "menepuk-nepuk"],
    ["椅子", "yǐ zi", "chair's", "kerusi punya"],
    ["扶手", "fú shǒu", "armrest", "pemegang tangan"],
    ["，", "", "", ""],
    ["兴奋得", "xīng fèn de", "so excited until", "tersangat teruja sehingga"],
    ["双眼", "shuāng yǎn", "both eyes", "kedua-dua belah mata"],
    ["发出光来", "fā chū guāng lái", "emitting light / shining", "mengeluarkan cahaya / bersinar-sinar"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 2 段

    ["我", "wǒ", "I", "Saya"],
    ["环视四周", "huán shì sì zhōu", "looked around", "memandang keliling / meninjau sekeliling"],
    ["，", "", "", ""],
    ["发现了", "fā xiàn le", "discovered / found", "menemui / mendapati"],
    ["埃里克", "āi lǐ kè", "Eric's", "Eric punya"],
    ["兴奋的", "xīng fèn de", "excited's", "teruja punya"],
    ["来源", "lái yuán", "source", "punca / sumber"],
    ["。", "", "", ""],
    ["那是一个", "nà shì yí gè", "That was an", "Ia merupakan seorang"],
    ["老人", "lǎo rén", "old man", "orang tua"],
    ["，", "", "", ""],
    ["穿着", "chuān zhe", "wearing", "memakai"],
    ["一件", "yí jiàn", "a (measure word for coat)", "sehelai"],
    ["沾满", "zhān mǎn", "covered with / stained with", "dipenuhi dengan / lumuran"],
    ["油污", "yóu wū", "grease / oil stains", "kesan minyak / kotoran minyak"],
    ["并且", "bìng qiě", "and moreover", "serta / lagipun"],
    ["已经", "yǐ jīng", "already", "sudah pun"],
    ["破烂不堪的", "pò làn bù kān de", "tattered and torn", "koyak-rabak / buruk sangat"],
    ["外套", "wài tào", "coat / jacket", "baju luar / jaket"],
    ["，", "", "", ""],
    ["裤子", "kù zi", "trousers / pants", "seluar"],
    ["又宽又大", "yòu kuān yòu dà", "wide and big", "longgar dan besar"],
    ["，", "", "", ""],
    ["只剩下", "zhǐ shèng xià", "only left", "hanya tinggal"],
    ["了", "le", "particle", ""],
    ["半截", "bàn jié", "half a section", "separuh / setengah bahagian"],
    ["，", "", "", ""],
    ["脚上的", "jiǎo shàng de", "on the feet's", "pada kaki punya"],
    ["鞋", "xié", "shoes", "kasut"],
    ["也破了", "yě pò le", "also broken / torn", "pun dah koyak"],
    ["，", "", "", ""],
    ["脚趾", "jiǎo zhǐ", "toes", "jari kaki"],
    ["露出了", "lù chū le", "revealed / exposed", "terkeluar dari / menonjol"],
    ["鞋外", "xié wài", "outside the shoes", "luar kasut"],
    ["。", "", "", ""],
    ["我们", "wǒ men", "We", "Kami"],
    ["由于", "yóu yú", "because / due to", "oleh kerana / disebabkan"],
    ["离他", "lí tā", "from him", "jarak dari dia"],
    ["太远", "tài yuǎn", "too far", "terlalu jauh"],
    ["而", "ér", "and thereby", "maka"],
    ["没有", "méi yǒu", "did not", "tidak"],
    ["闻到", "wén dào", "smell", "terbau"],
    ["他身上的", "tā shēn shàng de", "on his body's", "pada badan dia punya"],
    ["臭味", "chòu wèi", "bad smell / odor", "bau busuk"],
    ["，", "", "", ""],
    ["但我", "dàn wǒ", "but I", "namun saya"],
    ["敢肯定", "gǎn kěn dìng", "dare to be sure / certain", "berani memastikan / pasti"],
    ["他自己", "tā zì jǐ", "he himself", "dia sendiri"],
    ["一定", "yí dìng", "definitely", "pasti"],
    ["能闻到", "néng wén dào", "can smell", "boleh bau"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 3 段

    ["他正在", "tā zhèng zài", "He was currently", "Dia sedang"],
    ["招手", "zhāo shǒu", "waving hands", "melambai tangan"],
    ["，", "", "", ""],
    ["然后", "rán hòu", "then", "kemudian"],
    ["拍起了", "pāi qǐ le", "started clapping", "mula menepuk"],
    ["巴掌", "bā zhǎng", "palms (clapping)", "tangan"],
    ["。", "", "", ""],
    ["“", "", "", ""],
    ["嘿", "hēi", "Hey", "Hei"],
    ["，", "", "", ""],
    ["过来", "guò lái", "come over", "datang ke mari"],
    ["，", "", "", ""],
    ["宝贝", "bǎo bèi", "baby", "sayang / sayang"],
    ["，", "", "", ""],
    ["到这边来", "dào zhè biān lái", "come to this side", "datang ke sebelah sini"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["看到你了", "kàn dào nǐ le", "saw you", "nampak kamu dah"],
    ["，", "", "", ""],
    ["小伙子", "xiǎo huǒ zi", "young fellow / lad", "budak lelaki / anak muda"],
    ["。", "", "", ""],
    ["”", "", "", ""],
    ["老人", "lǎo rén", "The old man", "Orang tua itu"],
    ["对", "duì", "towards", "kepada"],
    ["埃里克", "āi lǐ kè", "Eric", "Eric"],
    ["喊道", "hǎn dào", "shouted", "melaung / menjerit"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["和", "hé", "and", "dan"],
    ["丈夫", "zhàng fu", "husband", "suami"],
    ["交换了", "jiāo huàn le", "exchanged", "saling bertukar"],
    ["一下", "yí xià", "once (expression)", "sekali"],
    ["眼神", "yǎn shén", "glance / expression in eyes", "pandangan mata"],
    ["：", "", "", ""],
    ["那个", "nà gè", "that", "orang tua yang"],
    ["古怪", "gǔ guài", "eccentric / weird", "pelik / aneh"],
    ["而且", "ér qiě", "and furthermore", "serta / dan juga"],
    ["令人讨厌的", "lìng rén tǎo yàn de", "annoying / disgusting", "menjengkelkan / dibenci"],
    ["老家伙", "lǎo jiā huo", "old fellow / guy", "tua bangka"],
    ["正在", "zhèng zài", "is currently", "sedang"],
    ["骚扰", "sāo rǎo", "harassing", "mengganggu / mengusik"],
    ["我们", "wǒ men", "us", "kami punya"],
    ["可爱的", "kě ài de", "lovely / cute", "yang comel"],
    ["儿子", "ér zi", "son", "anak lelaki"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 4 段

    ["我们", "wǒ men", "We", "Kami"],
    ["点的", "diǎn de", "ordered", "yang dipesan punya"],
    ["东西", "dōng xi", "things / food", "makanan / barang"],
    ["端上来了", "duān shàng lái le", "served up", "dihidangkan datang"],
    ["，", "", "", ""],
    ["那个", "nà gè", "that", "orang tua itu"],
    ["老人", "lǎo rén", "old man", "tua"],
    ["又在", "yòu zài", "again at", "pula di"],
    ["对面", "duì miàn", "opposite side", "sebelah depan / bertentangan"],
    ["开始", "kāi shǐ", "start", "mula"],
    ["大喊", "dà hǎn", "shouting loudly", "melaung kuat"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["你知道", "nǐ zhī dào", "you know", "Kamu tahu kah"],
    ["那些是", "nà xiē", "those are", "itu semua adalah"],
    ["小馅饼", "xiǎo xiàn bǐng", "small patties / pies", "lempeng kecil / pai kecil"],
    ["吗", "ma", "particle", "kah"],
    ["？", "", "", ""],
    ["你会玩", "nǐ huì wán", "can you play", "kamu pandai main"],
    ["躲躲猫", "duǒ duǒ māo", "peek-a-boo / hide and seek", "cak-ba / main sembunyi-sembunyi"],
    ["吗", "ma", "particle", "kah"],
    ["？", "", "", ""],
    ["哈", "hā", "Ha", "Ha"],
    ["！", "", "", ""],
    ["瞧", "qiáo", "look", "tengok / lihat"],
    ["，", "", "", ""],
    ["这", "zhè", "this", "ini"],
    ["小家伙", "xiǎo huǒ zi", "little fellow", "budak kecil"],
    ["会玩", "huì wán", "can play", "pandai main"],
    ["躲躲猫", "duǒ duǒ māo", "peek-a-boo", "cak-ba"],
    ["了", "le", "particle", ""],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 5 段

    ["没有谁", "méi yǒu shéi", "Nobody", "Tidak ada sesiapa pun"],
    ["会认为", "huì rèn wéi", "would think", "akan menyangka"],
    ["那个", "nà gè", "that", "orang tua itu"],
    ["老人", "lǎo rén", "old man", "tua"],
    ["是在", "shì zài", "was doing", "sedang"],
    ["故作姿态", "gù zuò zī tài", "putting on an act / posing", "berpura-pura / berlagak sahaja"],
    ["，", "", "", ""],
    ["但", "dàn", "but", "namun / tetapi"],
    ["我", "wǒ", "I", "saya"],
    ["和", "hé", "and", "dan"],
    ["丈夫", "zhàng fu", "husband", "suami"],
    ["尴尬极了", "gān gà jí le", "extremely embarrassed", "merasa tersangat janggal / malu"],
    ["，", "", "", ""],
    ["我们", "wǒ men", "We", "Kami"],
    ["默默地", "mò mò de", "silently", "dengan senyap-senyap / membisu"],
    ["吃着", "chī zhe", "eating", "sedang makan"],
    ["，", "", "", ""],
    ["埃里克", "āi lǐ kè", "Eric", "Eric"],
    ["却", "què", "however", "sebaliknya / pula"],
    ["不肯", "bù kěn", "unwilling to", "enggan / tidak mahu"],
    ["安静", "ān jìng", "be quiet", "senyap / bertenang"],
    ["。", "", "", ""],
    ["他", "tā", "he", "Dia"],
    ["在那个", "zài nà gè", "under that", "di bawah orang tua itu punya"],
    ["老人的", "lǎo rén de", "old man's", "tua punya"],
    ["怂恿下", "sǒng yǒng xià", "instigation / encouragement", "hasutan / galakan"],
    ["玩起了", "wán qǐ le", "started playing", "mula bermain"],
    ["躲躲猫", "duǒ duǒ māo", "peek-a-boo", "cak-ba"],
    ["游戏", "yóu xì", "game", "permainan"],
    ["。", "", "", ""],
    ["他在", "tā zài", "he in", "Dia di antara"],
    ["餐桌", "cān zhuō", "dining tables", "meja makan"],
    ["之间", "zhī jiān", "between", "antara"],
    ["跑来跑去", "pǎo lái pǎo qù", "running back and forth", "berlari ke sana ke mari"],
    ["，", "", "", ""],
    ["当他", "dāng tā", "when he", "apabila dia"],
    ["躲得", "duǒ de", "hid (with description)", "bersembunyi dengan"],
    ["很好", "hěn hǎo", "very well", "sangat baik"],
    ["，", "", "", ""],
    ["老人", "lǎo rén", "the old man", "orang tua itu"],
    ["看不到他", "kàn bú dào tā", "cannot see him", "tidak nampak dia"],
    ["表示", "biǎo shì", "expressing / indicating", "menunjukkan tanda"],
    ["认输时", "rèn shū shí", "admit defeat", "mengaku kalah"],
    ["，", "", "", ""],
    ["他就", "tā jiù", "he then", "dia terus"],
    ["咯咯笑着", "gē gē xiào zhe", "giggle / chuckling", "ketawa mengekek / mengekek riang"],
    ["跑出来", "pǎo chū lái", "run out", "berlari keluar"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["和", "hé", "and", "dan"],
    ["丈夫", "zhàng fu", "husband", "suami"],
    ["都觉得", "dōu jué de", "all felt", "pun berpendapat"],
    ["，", "", "", ""],
    ["埃里克", "āi lǐ kè", "Eric", "Eric"],
    ["从来没", "cóng lái méi", "never before", "tidak pernah sekali-kali"],
    ["玩得", "wán de", "played (description)", "bermain dengan"],
    ["这么开心过", "zhè me kāi xīn guò", "so happy before", "sebegitu seronok sekali"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 6 段

    ["我们", "wǒ men", "We", "Kami"],
    ["用完了餐", "yòng wán le cān", "finished the meal", "selesai makan nasi"],
    ["，", "", "", ""],
    ["丈夫", "zhàng fu", "husband", "suami saya"],
    ["先去", "xiān qù", "first went to", "terlebih dahulu pergi ke"],
    ["停车场", "tíng chē chǎng", "parking lot", "tempat letak kereta"],
    ["取车", "qǔ chē", "fetch the car", "mengambil kereta"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["与", "yǔ", "and", "serta / dengan"],
    ["埃里克", "āi lǐ kè", "Eric", "Eric"],
    ["留下来", "liú xià lái", "stayed behind", "tinggal di dalam untuk"],
    ["结帐", "jié zhàng", "settle the bill", "membayar bil / kaunter"],
    ["。", "", "", ""],
    ["结帐", "jié zhàng", "After settling bill", "Selesai bayar bil"],
    ["后", "hòu", "after", "selepas itu"],
    ["往外走", "wǎng wài zǒu", "walking outwards", "ketika melangkah keluar"],
    ["时", "shí", "when", "waktu"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["发现", "fā xiàn", "discovered", "mendapati"],
    ["那个", "nà gè", "that", "orang tua"],
    ["老人", "lǎo rén", "old man", "itu"],
    ["正", "zhèng", "was currently", "sedang"],
    ["泰然自若地", "tài rán zì ruò de", "calmly and composedly", "dengan bersahaja / tenang tanpa sebarang rupa bersalah"],
    ["坐在", "zuò zài", "sitting on", "duduk di"],
    ["餐厅门口", "cān tīng mén kǒu", "restaurant entrance", "pintu masuk restoran"],
    ["旁边", "páng biān", "beside / side", "tepi"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["顿时", "dùn shí", "instantly", "terus / seketika itu"],
    ["愣在", "lèng zài", "stunned at", "terpaku di"],
    ["那里", "nà lǐ", "there", "sana"],
    ["，", "", "", ""],
    ["只希望", "zhǐ xī wàng", "only hope", "hanya berharap"],
    ["在", "zài", "before", "sebelum"],
    ["他对", "tā duì", "he to", "dia kepada"],
    ["埃里克", "āi lǐ kè", "Eric", "Eric"],
    ["说话", "shuō huà", "speak words", "bercakap"],
    ["之前", "zhī qián", "before", "apa-apa"],
    ["，", "", "", ""],
    ["让我们", "ràng wǒ men", "let us", "biarkan kami"],
    ["离开", "lí kāi", "leave", "melangkah keluar dari / meninggalkan"],
    ["这里吧", "zhè lǐ ba", "here", "tempat ini lah"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 7 段

    ["当我", "dāng wǒ", "When I", "Apabila saya"],
    ["走近", "zǒu jìn", "walked near", "melangkah dekat ke"],
    ["那个", "nà gè", "that", "orang tua"],
    ["老人", "lǎo rén", "old man", "itu"],
    ["时", "shí", "when", "ketika"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["背过脸", "bèi guò liǎn", "turned my face away", "memalingkan muka ke arah lain"],
    ["，", "", "", ""],
    ["因为", "yīn wèi", "because", "kerana"],
    ["不想", "bù xiǎng", "do not want to", "tidak mahu"],
    ["闻到", "wén dào", "smell", "terbau"],
    ["他身上", "tā shēn shàng", "his body", "pada badan dia"],
    ["散发出来的", "sàn fā chū lái de", "emitted / sent out's", "yang dikeluarkan punya"],
    ["味道", "wèi dào", "odor / smell", "bau busuk"],
    ["。", "", "", ""],
    ["此时", "cǐ shí", "At this moment", "Pada waktu ini"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["紧紧", "jǐn jǐn", "tightly", "dengan erat / kuat"],
    ["抓着", "zhuā zhe", "grabbing", "memegang"],
    ["埃里克", "āi lǐ kè", "Eric's", "Eric punya"],
    ["小手", "xiǎo shǒu", "small hand", "tangan kecil"],
    ["，", "", "", ""],
    ["生怕", "shēng pà", "for fear that", "takut sangat kalau-kalau"],
    ["谁会", "shéi huì", "anyone would", "ada sesiapa yang akan"],
    ["把它", "bǎ tā", "him (object particle)", "meragutnya / mengambilnya"],
    ["抢走", "qiǎng zǒu", "snatch away", "lari pergi"],
    ["一样", "yí yàng", "the same as", "sedemikian"],
    ["。", "", "", ""],
    ["开水", "", "", ""],
    ["可是", "kě shì", "However", "Tetapi / sebaliknya"],
    ["，", "", "", ""],
    ["埃里克", "āi lǐ kè", "Eric", "Eric"],
    ["挣脱了", "zhèng tuō le", "broke free from", "merentap lepas dari / melepaskan diri dari"],
    ["我的", "wǒ de", "my", "saya punya"],
    ["手", "shǒu", "hand", "genggaman tangan"],
    ["，", "", "", ""],
    ["向", "xiàng", "towards", "ke arah"],
    ["那老人的", "nà lǎo rén de", "that old man's", "orang tua itu punya"],
    ["怀里", "huái lǐ", "bosom / arms", "dakapan"],
    ["投去", "tóu qù", "threw into", "meluru masuk / mencampak diri"],
    ["。", "", "", ""],
    ["事情", "shì qing", "The matter / event", "Perkara ini"],
    ["发生得", "fā shēng de", "happened (description)", "berlaku with"],
    ["太突然了", "tài tū rán le", "too suddenly", "tersangat tiba-tiba"],
    ["，", "", "", ""],
    ["在", "zài", "before / at", "sebelum"],
    ["我", "wǒ", "I", "saya"],
    ["还没来得及", "hái méi lái de jí", "have not had time yet to", "masih belum sempat untuk"],
    ["阻止", "zǔ zhǐ", "prevent / stop", "menghalang"],
    ["，", "", "", ""],
    ["一个", "yí gè", "a", "seorang"],
    ["浑身", "hún shēn", "all over the body", "seluruh badan"],
    ["臭味的", "chòu wèi de", "smelly", "berbau busuk punya"],
    ["老人", "lǎo rén", "old man", "orang tua"],
    ["和", "hé", "and", "dan"],
    ["一个", "yí gè", "a", "seorang"],
    ["可爱的", "kě ài de", "lovely / cute", "yang comel"],
    ["小男孩", "xiǎo nán hái", "little boy", "budak lelaki kecil"],
    ["之间的", "zhī jiān de", "between's", "antara punya"],
    ["关系", "guān xi", "relationship", "hubungan"],
    ["就", "jiù", "then", "pun / terus"],
    ["达到了", "dào dá le", "reached", "mencapai tahap"],
    ["升华", "shēng huá", "sublimation / deep elevation", "suci / murni / peningkatan rohani"],
    ["，", "", "", ""],
    ["仿佛", "fǎng fú", "as if", "seolah-olah bagaikan"],
    ["深爱着的", "shēn ài zhe de", "deeply loving's", "sangat menyayangi punya"],
    ["祖孙俩", "zǔ sūn liǎ", "grandparent and grandchild pair", "datuk dan cucu"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 8 段

    ["埃里克", "āi lǐ kè", "Eric", "Eric"],
    ["温顺地", "wēn shùn de", "meekly / docilely", "dengan patuh / jinaknya / lembut"],
    ["靠在", "kào zài", "leaned on", "bersandar pada"],
    ["老人", "lǎo rén", "old man's", "orang tua itu punya"],
    ["那穿着", "nà chuān zhe", "that wearing", "yang memakai"],
    ["破烂", "pò làn", "tattered", "koyak-rabak punya"],
    ["衣服的", "yī fu de", "clothes'", "baju"],
    ["肩膀", "jiān bǎng", "shoulder", "bahu"],
    ["上", "shàng", "on", "atas"],
    ["。", "", "", ""],
    ["他把", "bǎ tā", "he object particle", "Dia membawa"],
    ["他对人的", "tā duì rén de", "his towards people's", "dia terhadap manusia punya"],
    ["完全", "wán quán", "complete / absolute", "sepenuhnya / mutlak"],
    ["信任", "xìn rèn", "trust", "kepercayaan"],
    ["以及", "yǐ jí", "as well as", "serta / dan juga"],
    ["它的", "tā de", "his", "dia punya"],
    ["爱", "ài", "love", "kasih sayang"],
    ["付诸了", "fù zhū le", "put into (action)", "menterjemahkan ke dalam"],
    ["行动", "xíng dòng", "action", "tindakan nyata"],
    ["。", "", "", ""],
    ["老人", "lǎo rén", "The old man", "Orang tua itu"],
    ["闭起了", "bì qǐ le", "closed up", "memejamkan"],
    ["眼睛", "yǎn jing", "eyes", "mata"],
    ["，", "", "", ""],
    ["泪水", "lèi shuǐ", "tears", "air mata"],
    ["沾满了", "zhān mǎn le", "covered with / wet", "membasahi seluruh"],
    ["他的", "tā de", "his", "dia punya"],
    ["睫毛", "jié máo", "eyelashes", "bulu mata"],
    ["，", "", "", ""],
    ["然后", "rán hòu", "then", "kemudian"],
    ["滑下", "huá xià", "slid down", "mengalir turun ke"],
    ["脸颊", "liǎn jiá", "cheeks", "pipi"],
    ["，", "", "", ""],
    ["他那", "tā nà", "his that", "dia punya yang"],
    ["苍老的", "cāng lǎo de", "aged / old", "tua lama"],
    ["手", "shǒu", "hands", "tangan"],
    ["布满了", "bù mǎn le", "covered with", "dipenuhi dengan"],
    ["污垢", "wū gòu", "dirt / filth", "kotoran / daki"],
    ["、", "", "", ""],
    ["伤痕", "shāng hén", "scars / bruises", "kesan luka / lebam"],
    ["以及", "yǐ jí", "as well as", "serta"],
    ["老茧", "lǎo jiǎn", "calluses", "kemalan / kulit keras 'kematu'"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["轻轻", "qīng qīng", "gently", "perlahan-lahan"],
    ["抱着", "bào zhe", "holding / hugging", "mendakap / memeluk"],
    ["孩子", "hái zi", "child", "anak itu"],
    ["，", "", "", ""],
    ["温柔地", "wēn róu de", "gently / tenderly", "dengan penuh lembut / mesra"],
    ["抚摸着", "fǔ mō zhe", "stroking / caressing", "mengusap-usap / membelai"],
    ["孩子的", "hái zi de", "child's", "anak punya"],
    ["背", "bèi", "back", "belakang badan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 9 段

    ["没有哪", "méi yǒu nǎ", "There were no", "Tidak ada mana-mana"],
    ["两个人", "liǎng gè rén", "two people", "dua orang manusia"],
    ["会像", "huì xiàng", "would be like", "akan bagaikan"],
    ["他们那样", "tā men nà yàng", "them like that", "mereka sedemikian"],
    ["，", "", "", ""],
    ["在这么短的", "zài zhè me duǎn de", "in such a short", "dalam tempoh yang tersangat singkat punya"],
    ["时间", "shí jiān", "time", "masa"],
    ["就", "jiù", "then", "terus"],
    ["产生", "chǎn shēng", "generate / produce", "melahirkan / membuahkan"],
    ["这样", "zhè yàng", "such a", "sebegini punya"],
    ["深厚的", "shēn hòu de", "deep and profound", "mendalam / tebal"],
    ["感情", "gǎn qíng", "affection / emotion", "perasaan kasih sayang"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["站在", "zhàn zài", "standing at", "berdiri di"],
    ["那里", "nà lǐ", "there", "sana"],
    ["，", "", "", ""],
    ["呆住了", "dāi zhù le", "dumbstruck / rooted in place", "terpaku / tergamam"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 10 段

    ["老人", "lǎo rén", "The old man", "Orang tua itu"],
    ["怜爱地", "lián ài de", "lovingly / tenderly", "dengan penuh belas kasihan dan kasih sayang"],
    ["看着", "kàn zhe", "looking at", "memandang"],
    ["怀里的", "huái lǐ de", "in the bosom's", "dalam dakapan punya"],
    ["埃里克", "āi lǐ kè", "Eric", "Eric"],
    ["。", "", "", ""],
    ["我知道", "wǒ zhī dào", "I knew", "Saya tahu"],
    ["，", "", "", ""],
    ["埃里克", "āi lǐ kè", "Eric", "Eric"],
    ["离开", "lí kāi", "leaving", "melangkah keluar dari / meninggalkan"],
    ["他的", "tā de", "his", "dia punya"],
    ["怀抱", "huái bào", "embrace / arms", "dakapan"],
    ["，", "", "", ""],
    ["对他来说", "duì tā lái shuō", "for him was", "kepada dia punya diri adalah"],
    ["是一件", "shì yí jiàn", "was a", "merupakan satu perkara yang"],
    ["痛苦的事情", "tòng kǔ de shì qing", "painful thing", "amat perit / menyakitkan"],
    ["。", "", "", ""],
    ["但", "dàn", "but", "Namun"],
    ["埃里克", "āi lǐ kè", "Eric", "Eric"],
    ["最终", "zuì zhōng", "eventually / in the end", "akhirnya pada kesudahannya"],
    ["还是", "hái shì", "still", "tetap"],
    ["回到了", "huí dào le", "returned to", "kembali ke"],
    ["我的", "wǒ de", "my", "saya punya"],
    ["身边", "shēn biān", "side", "sisi / tepi"],
    ["。", "", "", ""],
    ["老人", "lǎo rén", "The old man", "Orang tua itu"],
    ["激动地", "jī dòng de", "emotionally / excitedly", "dengan nada penuh emosi / tergetar"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["上帝", "shàng dì", "God", "Tuhan / Allah"],
    ["保佑你", "bǎo yòu nǐ", "bless you", "merahmati kamu / melindungi kamu"],
    ["，", "", "", ""],
    ["夫人", "fū ren", "Madam / Ma'am", "puan"],
    ["，", "", "", ""],
    ["谢谢你", "xiè xie nǐ", "thank you", "terima kasih"],
    ["给了我", "gěi le wǒ", "giving me", "kerana memberi saya"],
    ["一份", "yí fèn", "a (measure word for gift)", "satu"],
    ["最好的", "zuì hǎo de", "the best", "paling baik punya"],
    ["圣诞礼物", "shèng dàn lǐ wù", "Christmas present", "hadiah Krismas"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 11 段

    ["我", "wǒ", "I", "Saya"],
    ["没有说", "méi yǒu shuō", "did not say", "tidak berkata"],
    ["一个字", "yí gè zì", "one single word", "sepatah perkataan pun"],
    ["，", "", "", ""],
    ["因为", "yīn wèi", "because", "kerana"],
    ["我知道", "wǒ zhī dào", "I knew", "saya tahu"],
    ["我", "wǒ", "I", "saya"],
    ["无法", "wú fǎ", "unable to / no way to", "tidak layak / tidak berupaya untuk"],
    ["承受", "chéng shòu", "bear / accept (the gratitude)", "menerima / menanggung"],
    ["这一句", "zhè yí jù", "this sentence of", "ayat ini punya"],
    ["真诚的", "zhēn chéng de", "sincere", "keikhlasan yang amat sangat"],
    ["感谢", "gǎn xiè", "thanks / gratitude", "ucapan terima kasih"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 12 段

    ["我", "wǒ", "I", "Saya"],
    ["抱起", "bào qǐ", "picked up / scooped up", "mengangkat mendakap up"],
    ["埃里克", "āi lǐ kè", "Eric", "Eric"],
    ["，", "", "", ""],
    ["向", "xiàng", "towards", "ke arah"],
    ["我们的", "wǒ men de", "our", "kami punya"],
    ["汽车", "qì chē", "car", "kereta"],
    ["跑去", "pǎo qù", "ran towards", "berlari menuju"],
    ["。", "", "", ""],
    ["在", "zài", "in / inside", "Di dalam"],
    ["车上", "chē shàng", "the car", "kereta"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["紧紧", "jǐn jǐn", "tightly", "dengan erat / sekuat-kuatnya"],
    ["抱着", "bào zhe", "hugging", "memeluk"],
    ["埃里克", "āi lǐ kè", "Eric", "Eric"],
    ["，", "", "", ""],
    ["终于", "zhōng yú", "finally", "akhirnya"],
    ["忍不住", "rén bú zhù", "could not help but", "tidak dapat menahan diri lalu"],
    ["哭了", "kū le", "cried", "menangis mencucurkan air mata"],
    ["，", "", "", ""],
    ["边哭边说", "biān kū biān shuō", "weeping while speaking", "sambil menangis sambil berkata"],
    ["：", "", "", ""],
    ["上帝", "shàng dì", "God", "Ya Tuhan / Oh Allah"],
    ["，", "", "", ""],
    ["请宽恕我", "qǐng kuān shù wǒ", "please forgive me", "ampunilah saya / maafkanlah kekhilafan saya"],
    ["吧", "ba", "particle", "lah"],
    ["！", "", "", ""],

    ["\n", "", "", ""], // 👈 第 13 段

    ["我", "wǒ", "I", "Saya"],
    ["明白了", "míng bai le", "understood / realized", "telah sedar / faham sepenuhnya"],
    ["：", "", "", ""],
    ["那一刻", "nà yí kè", "at that moment", "pada saat itu"],
    ["，", "", "", ""],
    ["孩子", "hái zi", "the child", "anak kecil itu"],
    ["看到的", "kàn dào de", "saw's", "nampak punya perkara"],
    ["只是", "zhǐ shì", "only was", "hanyalah"],
    ["一个", "yí gè", "an", "seorang"],
    ["喜欢他的", "xǐ huan tā de", "who liked him's", "orang tua yang menyayanginya"],
    ["老人", "lǎo rén", "old man", "tua"],
    ["，", "", "", ""],
    ["而", "ér", "while / but on the other hand", "manakala / sebaliknya pula"],
    ["母亲", "mā ma", "the mother", "si ibu"],
    ["看到的", "kàn dào de", "saw's", "nampak punya perkara"],
    ["却", "què", "however", "hanyalah / sebaliknya"],
    ["只是一件", "zhǐ shì yí jiàn", "only was a piece of", "sekadar sehelai"],
    ["衣服", "yī fu", "clothes / outerwear", "pakaian usang / baju"],
    ["。", "", "", ""]
];
